version: "3.3"
services:

  datomic-pro:
    image: datomic-pro
    container_name: conj-datomic-pro
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-pro
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base

  datomic-free:
    image: datomic-free
    container_name: conj-datomic-free
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-free
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base


  datomicdb:
    image: datomic-pro
    # image: conj_datomicdb
    container_name: conj-datomicdb
    volumes:
      # - "./.data/datomicdb:/opt/datomic-pro/data"
      - "./.backups/datomicdb:/opt/backups"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4336:4336"
      - "4335:4335"
      - "4334:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/dev-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-pro

  # datomicdbprod:
  #   image: datomic-pro
  #   # image: conj_datomicdb
  #   container_name: conj-datomicdbprod
  #   # volumes:
  #   #   - "./.data/datomicdb:/opt/datomic-pro/data"
  #   # build:
  #   #   context: ./datomic-pro
  #   #   dockerfile: ./Dockerfile
  #   # ports:
  #   #   - "4336:4336"
  #   #   - "4335:4335"
  #   #   - "4334:4334"
  #     # - "9000:9000"
  #   # entrypoint: ./bin/transactor
  #   # command: ./bin/transactor ./config/dev-transactor.properties
  #   command: bash -c "./bin/transactor ./config/dev-transactor.properties"
  #   # command: config/dev-transactor.properties
  #   # command: tail -f /dev/null
  #   # command: bash c nrepl_clj
  #   # environment:
  #   #   - DISPLAY=10.0.75.1:0.0
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - datomic-pro


  datomicdbpeer:
    image: datomic-pro
    # image: conj_datomicdb
    container_name: conj-datomicdbpeer
    # volumes:
    #   - "./.data/datomicdb:/opt/datomic-pro/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    # command: ./bin/transactor ./config/dev-transactor.properties
    command: dockerize -wait http://create-dbs:8890/health -timeout 360s ./bin/run -m datomic.peer-server -h "0.0.0.0" -p 8998 -a myaccesskey,mysecret -d dayofdatomic,datomic:dev://datomicdb:4334/dayofdatomic -d movies,datomic:dev://datomicdb:4334/movies -d tutorial,datomic:dev://datomicdb:4334/tutorial
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-pro
    links:
      - datomicdb
      - create-dbs

  # waiter:
  #   image: aanand/wait
  #   links:
  #     - datomic-pro
  #     - transactor:datomicdb

  console:
    image: datomic-pro
    # image: conj_console
    container_name: conj-console
    # volumes:
    #   - ./.data/datomic-pro:/opt/datomic-pro
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    # entrypoint: ./bin/console -p 9000
    command: ./bin/console -p 9000 dev datomic:dev://datomicdb:4334
    # command: dev datomic:dev://datomicdb:4334
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-pro
      - datomicdb
    links:
      - datomicdb

  datomicdbfree:
    image: datomic-free
    # image: conj_datomicdb
    container_name: conj-datomicdbfree
    # volumes:
    #   - "./.data/datomicdbfree:/opt/datomic-free/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4436:4336"
      - "4435:4335"
      - "4434:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/free-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-free

  create-dbs:
    image: create-dbs
    container_name: conj-create-dbs
    volumes:
      - ./create-dbs:/opt/code/app
    build:
      context: ./create-dbs
      dockerfile: ./Dockerfile
    ports:
    #   - 35544:35543
      - 8890:8890
    command: bash c init
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - clj
    healthcheck:
        test: ["CMD", "curl", "-f", "localhost:8890"]
        interval: 1s
        timeout: 0s
        retries: 100

  clj:
    image: clj
    container_name: conj-clj
    volumes:
      - ./clj:/opt/code/app
    build:
      context: ./clj
      dockerfile: ./Dockerfile
    ports:
      - 35540:35543
      - 7880:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - datomicdbfree

  app-clj:
    image: app-clj
    container_name: conj-app-clj
    volumes:
      - ./app-clj:/opt/code/app
    build:
      context: ./app-clj
      dockerfile: ./Dockerfile
    ports:
      - 35543:35543
      - 7888:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - clj
      - datomicdb
      - datomicdbfree

  app-pro:
    image: app-pro
    container_name: conj-app-pro
    volumes:
      - ./app-pro:/opt/code/app
    build:
      context: ./app-pro
      dockerfile: ./Dockerfile
    ports:
      - 35544:35543
      - 7889:7888
      - 8891:8890
      # - 8892:8080
      # - 8893:8081

    command: bash c init
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - clj
      - datomicdb
      - datomicdbpeer

  app-free:
    image: app-free
    container_name: conj-app-free
    volumes:
      - ./app-free:/opt/code/app
    build:
      context: ./app-free
      dockerfile: ./Dockerfile
    ports:
      - 35545:35543
      - 7899:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - clj
      - datomicdb
      - datomicdbfree

  load-mbrainz:
    image: load-mbrainz
    container_name: conj-load-mbrainz
    build:
      context: ./load-mbrainz
      dockerfile: ./Dockerfile
    command: bash c init
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - clj
      - datomicdb
      - datomicdbfree
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8890"]
      interval: 1s
      timeout: 0s
      retries: 100

  load-codeqs:
    image: load-codeqs
    container_name: conj-load-codeqs
    build:
      context: ./load-codeqs
      dockerfile: ./Dockerfile
    command: sh load.sh
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - clj
      - datomicdb
      - datomicdbfree


  postgres:
    image: postgres:11.1
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: datomic
      POSTGRES_PASSWORD: datomic

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8088:8080




  app-query:
    image: app-query
    container_name: conj-app-query
    volumes:
      - ./app-query:/opt/code/app
    build:
      context: ./app-query
      dockerfile: ./Dockerfile
    ports:
      # - 35544:35543
      - 7778:7888
      # - 8891:8890
      - 8892:8080
      - 8893:8081
    command: dockerize -wait http://load-mbrainz:8890/health -timeout 360s  bash c init
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - clj
      - datomicdb
      - datomicdbpeer
      - datomicdbfree
      - load-mbrainz



  wui:
    image: wui
    # container_name: dq-dockerwheel
    volumes:
      - ./wui:/clj
    build:
      context: ./wui
      dockerfile: ./Dockerfile
    ports:
      - 3449:3449
      - 7788:7888
    # command: tail -f /dev/null
    # command: lein do clean, figwheel
    command: bash c init
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      # - app-pro
      - app-free
      - app-query
    # depends_on:
    #   - base



  todomvc:
    image: todomvc
    # container_name: dq-dockerwheel
    volumes:
      - ./todomvc:/clj
    build:
      context: ./todomvc
      dockerfile: ./Dockerfile
    ports:
      - 3448:3448
      - 7878:7888
    # command: tail -f /dev/null
    # command: lein do clean, figwheel
    command: bash c init
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # links:
      # - app-pro
      # - app-free
      # - app-query
    # depends_on:
    #   - base


  app-exp:
    image: app-exp
    container_name: conj-app-exp
    volumes:
      - ./app-exp:/opt/code/app
    build:
      context: ./app-exp
      dockerfile: ./Dockerfile
    ports:
      # - 35544:35543
      - 7890:7888
      # - 8891:8890
      - 8899:8080
    command: dockerize -wait http://load-mbrainz:8890/health -timeout 360s  bash c init
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - clj
      - datomicdb
      - datomicdbpeer
      - datomicdbfree
      - load-mbrainz
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq/isolated.conf:/etc/rabbitmq/rabbitmq.config