version: "3.3"
services:

  datomic-pro:
    image: datomic-pro
    container_name: clj-datomic-pro
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-pro
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base

  datomic-free:
    image: datomic-free
    container_name: clj-datomic-free
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-free
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base


  datomicdb:
    image: datomic-pro
    # image: conj_datomicdb
    container_name: clj-datomicdb
    volumes:
      - "./.data/datomicdb:/opt/datomic-pro/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4336:4336"
      - "4335:4335"
      - "4334:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/dev-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-pro

  # waiter:
  #   image: aanand/wait
  #   links:
  #     - datomic-pro
  #     - transactor:datomicdb

  console:
    image: datomic-pro
    # image: conj_console
    container_name: clj-console
    # volumes:
    #   - ./.data/datomic-pro:/opt/datomic-pro
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    # entrypoint: ./bin/console -p 9000
    command: ./bin/console -p 9000 dev datomic:dev://datomicdb:4334
    # command: dev datomic:dev://datomicdb:4334
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-pro
      - datomicdb
    links:
      - datomicdb


  datomicdbfree:
    image: datomic-free
    # image: conj_datomicdb
    container_name: clj-datomicdbfree
    volumes:
      - "./.data/datomicdbfree:/opt/datomic-free/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4436:4336"
      - "4435:4335"
      - "4434:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/free-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-free


  clj:
    image: clj
    container_name: clj-clj
    volumes:
      - ./clj:/opt/code/app
    build:
      context: ./clj
      dockerfile: ./Dockerfile
    ports:
      - 35540:35543
      - 7880:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - datomicdbfree

  app-clj:
    image: app-clj
    container_name: clj-app-clj
    volumes:
      - ./app-clj:/opt/code/app
    build:
      context: ./app-clj
      dockerfile: ./Dockerfile
    ports:
      - 35543:35543
      - 7888:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - datomicdbfree

  app-pro:
    image: app-pro
    container_name: clj-app-pro
    volumes:
      - ./app-pro:/opt/code/app
    build:
      context: ./app-pro
      dockerfile: ./Dockerfile
    ports:
      - 35544:35543
      - 7889:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - datomicdbfree

  app-free:
    image: app-free
    container_name: clj-app-free
    volumes:
      - ./app-free:/opt/code/app
    build:
      context: ./app-free
      dockerfile: ./Dockerfile
    ports:
      - 35545:35543
      - 7899:7888
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdb
      - datomicdbfree

  load-mbrainz:
    image: load-mbrainz
    container_name: clj-load-mbrainz
    build:
      context: ./load-mbrainz
      dockerfile: ./Dockerfile
    command: sh mbrainz.sh ; tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - clj
      - datomicdb

  load-codeqs:
    image: load-codeqs
    container_name: clj-load-codeqs
    build:
      context: ./load-codeqs
      dockerfile: ./Dockerfile
    command: sh load.sh
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - clj
      - datomicdb
