FROM clj


RUN git clone https://github.com/Datomic/codeq
    
COPY ./codeq.sh $DATOMIC_HOME

# RUN wget https://s3.amazonaws.com/mbrainz/datomic-mbrainz-1968-1973-backup-2017-07-20.tar -O mbrainz.tar && \
#     tar -xvf mbrainz.tar
